# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Elizabeth Walton.'
description: ''
permalink: pretty
logo: "../../../../../fall_23_logo_text.png"

# Pagination
#paginate: 5
#paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
subfolderitems:
      - name: "Elizabeth"
        url: "/elizabeth/"
        weight: 2
- #title: Cie Ring ; Ring ; Dial
 # url: /ring-ring-dial/
- title: Projects
  url: /projects/
- title: Calendar
  url: /calendar/
#title: Gallery
  #url: /gallery/
 #title: Blog
 # url: /blog/
- title: Contact 
  url: /contact/
- title: Fr 
  url: /fr/

navigation_footer:
- title: Instagram
  url: https://www.instagram.com/_elizabeth_walton_/

# Footer nav
#navigation_footer:
- #title: Last Updated: July 18, 2022
  #url : ""
#- title: Back to top
  #url: "#top"
 #- title: Instagram
   #url: "https://www.instagram.com/_elizabeth_walton_/"

# Collections
collections:
 posts:
    title: Projects # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: 
    feature_image: "../../../../../Website_drawing_2.png "
   

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
      
