# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Elizabeth Walton.'
description: 'This is my new website'
permalink: pretty
logo: "../Grey_white_prof_pic.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Projects
  url: /projects/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- #title: Last Updated: July 18, 2022
  #url : ""
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"  
   pages:
    title: Projects
    output: true
   # description: "my thesis work" 
   # feature_text: |
    #  Welcome to my projects
    feature_image: "https://picsum.photos/2560/600?image=866"
   

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
      
   #-
   # scope:
   #   path: ""
    #  type: "projs"
   # values:
      #layout: post # Set the default layout for pages
